# ──────────────────────────────────────────────────────────────────────
#  SymbolicPuzzle3D — Interactive Setup Script (Windows PowerShell)
# ──────────────────────────────────────────────────────────────────────
#  Run with: .\setup.ps1
# ──────────────────────────────────────────────────────────────────────

function Write-Banner {
    Write-Host ""
    Write-Host "╔══════════════════════════════════════════╗" -ForegroundColor Cyan
    Write-Host "║     SymbolicPuzzle3D — Setup Script      ║" -ForegroundColor Cyan
    Write-Host "╚══════════════════════════════════════════╝" -ForegroundColor Cyan
    Write-Host ""
}

function Write-Step  { param($msg) Write-Host "→ $msg" -ForegroundColor Cyan }
function Write-Ok    { param($msg) Write-Host "✓ $msg" -ForegroundColor Green }
function Write-Warn  { param($msg) Write-Host "⚠ $msg" -ForegroundColor Yellow }
function Write-Fail  { param($msg) Write-Host "✗ $msg" -ForegroundColor Red; exit 1 }

# ── Check Docker ──────────────────────────────────────────────────────
function Check-Docker {
    Write-Step "Checking Docker..."
    try {
        $null = & docker compose version 2>&1
        if ($LASTEXITCODE -ne 0) { throw }
        Write-Ok "Docker ready"
    } catch {
        Write-Fail "Docker not found or Docker Compose unavailable. Install from: https://docs.docker.com/get-docker/"
    }
}

# ── Generate random hex secret ─────────────────────────────────────────
function New-Secret {
    $bytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return -join ($bytes | ForEach-Object { $_.ToString("x2") })
}

# ── Load existing .env ─────────────────────────────────────────────────
function Get-EnvValue {
    param($key)
    if (Test-Path ".env") {
        $line = Get-Content ".env" | Where-Object { $_ -match "^$key=" } | Select-Object -First 1
        if ($line) { return $line.Split("=", 2)[1].Trim() }
    }
    return ""
}

# ── Setup .env ─────────────────────────────────────────────────────────
function Setup-Env {
    Write-Step "Setting up .env file..."

    if (Test-Path ".env") {
        Write-Warn ".env already exists — loading existing values"
    }

    Write-Host ""
    Write-Host "You need to set 2 secrets. Press Enter to auto-generate." -ForegroundColor White
    Write-Host ""

    # RSVS_API_KEY
    $existingKey = Get-EnvValue "RSVS_API_KEY"
    if ($existingKey) {
        Write-Ok "RSVS_API_KEY already set (keeping existing)"
        $apiKey = $existingKey
    } else {
        $autoKey = New-Secret
        Write-Host "RSVS_API_KEY" -ForegroundColor Cyan -NoNewline
        $input = Read-Host " (press Enter to auto-generate)"
        $apiKey = if ($input.Trim()) { $input.Trim() } else { $autoKey }
        Write-Ok "RSVS_API_KEY set"
    }

    # RSVS_SESSION_SECRET
    $existingSecret = Get-EnvValue "RSVS_SESSION_SECRET"
    if ($existingSecret) {
        Write-Ok "RSVS_SESSION_SECRET already set (keeping existing)"
        $sessionSecret = $existingSecret
    } else {
        $autoSecret = New-Secret
        Write-Host "RSVS_SESSION_SECRET" -ForegroundColor Cyan -NoNewline
        $input = Read-Host " (press Enter to auto-generate)"
        $sessionSecret = if ($input.Trim()) { $input.Trim() } else { $autoSecret }
        Write-Ok "RSVS_SESSION_SECRET set"
    }

    # Write .env
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    @"
# ── SymbolicPuzzle3D — Environment Variables ──
# Generated by setup.ps1 on $timestamp

# --- Secrets (required) ---
RSVS_API_KEY=$apiKey
RSVS_SESSION_SECRET=$sessionSecret

# --- Backend config ---
RSVS_HOST=0.0.0.0
RSVS_PORT=8000
RSVS_ATOM_DIR=/app/data
NODE_ENV=production

# --- CORS: comma-separated list of allowed frontend origins ---
RSVS_ALLOWED_ORIGINS=http://localhost:3000
"@ | Out-File -Encoding UTF8 -FilePath ".env"

    Write-Ok ".env written"
}

# ── Build & Start ──────────────────────────────────────────────────────
function Build-And-Start {
    Write-Step "Building Docker images (this may take a few minutes on first run)..."
    & docker compose build
    if ($LASTEXITCODE -ne 0) { Write-Fail "Docker build failed. Check output above." }

    Write-Step "Starting all services..."
    & docker compose up -d
    if ($LASTEXITCODE -ne 0) { Write-Fail "Docker compose up failed." }

    Write-Step "Waiting for backend to be healthy..."
    $healthy = $false
    for ($i = 0; $i -lt 20; $i++) {
        try {
            $res = Invoke-WebRequest -Uri "http://localhost:8000/health" -UseBasicParsing -TimeoutSec 3 -ErrorAction Stop
            if ($res.StatusCode -eq 200) { $healthy = $true; break }
        } catch {}
        Write-Host "." -NoNewline
        Start-Sleep -Seconds 3
    }
    Write-Host ""
    if (-not $healthy) {
        Write-Warn "Backend health check timed out — check: docker compose logs backend"
    }
}

# ── Done ───────────────────────────────────────────────────────────────
function Print-Done {
    Write-Host ""
    Write-Host "╔══════════════════════════════════════════╗" -ForegroundColor Green
    Write-Host "║            All services running!         ║" -ForegroundColor Green
    Write-Host "╚══════════════════════════════════════════╝" -ForegroundColor Green
    Write-Host ""
    Write-Host "  Frontend  →  " -NoNewline; Write-Host "http://localhost:3000" -ForegroundColor Cyan
    Write-Host "  Backend   →  " -NoNewline; Write-Host "http://localhost:8000" -ForegroundColor Cyan
    Write-Host "  API Docs  →  " -NoNewline; Write-Host "http://localhost:8000/docs" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  Stop all:  " -NoNewline; Write-Host "docker compose down" -ForegroundColor White
    Write-Host "  Logs:      " -NoNewline; Write-Host "docker compose logs -f" -ForegroundColor White
    Write-Host ""
}

# ── Main ───────────────────────────────────────────────────────────────
Write-Banner
Check-Docker
Setup-Env
Build-And-Start
Print-Done
