#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────
#  SymbolicPuzzle3D — Interactive Setup Script (Linux / macOS)
# ──────────────────────────────────────────────────────────────────────
set -euo pipefail

CYAN='\033[36m'; BOLD='\033[1m'; GREEN='\033[32m'
RED='\033[31m'; YELLOW='\033[33m'; RESET='\033[0m'

banner() {
  echo -e ""
  echo -e "${BOLD}${CYAN}╔══════════════════════════════════════════╗${RESET}"
  echo -e "${BOLD}${CYAN}║     SymbolicPuzzle3D — Setup Script      ║${RESET}"
  echo -e "${BOLD}${CYAN}╚══════════════════════════════════════════╝${RESET}"
  echo -e ""
}

step()  { echo -e "${BOLD}${CYAN}→ $1${RESET}"; }
ok()    { echo -e "${GREEN}✓ $1${RESET}"; }
warn()  { echo -e "${YELLOW}⚠ $1${RESET}"; }
fail()  { echo -e "${RED}✗ $1${RESET}"; exit 1; }

# ── Check Docker ──────────────────────────────────────────────────────
check_docker() {
  step "Checking Docker..."
  command -v docker &>/dev/null || fail "Docker not found. Install from https://docs.docker.com/get-docker/"
  docker compose version &>/dev/null || fail "Docker Compose not found. Make sure Docker Desktop is installed."
  ok "Docker ready"
}

# ── Generate random secret ─────────────────────────────────────────────
gen_secret() {
  if command -v openssl &>/dev/null; then
    openssl rand -hex 32
  else
    cat /dev/urandom | tr -dc 'a-f0-9' | head -c 64
  fi
}

# ── Setup .env ─────────────────────────────────────────────────────────
setup_env() {
  step "Setting up .env file..."

  if [ -f .env ]; then
    warn ".env already exists — loading existing values"
    source .env 2>/dev/null || true
  fi

  echo -e ""
  echo -e "${BOLD}You need to set 2 secrets. Press Enter to auto-generate.${RESET}"
  echo -e ""

  # RSVS_API_KEY
  if [ -z "${RSVS_API_KEY:-}" ]; then
    auto_key=$(gen_secret)
    echo -ne "${CYAN}RSVS_API_KEY${RESET} (press Enter to auto-generate): "
    read -r input_key
    RSVS_API_KEY="${input_key:-$auto_key}"
    ok "RSVS_API_KEY set"
  else
    ok "RSVS_API_KEY already set (keeping existing)"
  fi

  # RSVS_SESSION_SECRET
  if [ -z "${RSVS_SESSION_SECRET:-}" ]; then
    auto_secret=$(gen_secret)
    echo -ne "${CYAN}RSVS_SESSION_SECRET${RESET} (press Enter to auto-generate): "
    read -r input_secret
    RSVS_SESSION_SECRET="${input_secret:-$auto_secret}"
    ok "RSVS_SESSION_SECRET set"
  else
    ok "RSVS_SESSION_SECRET already set (keeping existing)"
  fi

  # Write .env
  cat > .env <<EOF
# ── SymbolicPuzzle3D — Environment Variables ──
# Generated by setup.sh on $(date)

# --- Secrets (required) ---
RSVS_API_KEY=${RSVS_API_KEY}
RSVS_SESSION_SECRET=${RSVS_SESSION_SECRET}

# --- Backend config ---
RSVS_HOST=0.0.0.0
RSVS_PORT=8000
RSVS_ATOM_DIR=/app/data
NODE_ENV=production

# --- CORS: comma-separated list of allowed frontend origins ---
RSVS_ALLOWED_ORIGINS=http://localhost:3000
EOF

  ok ".env written"
}

# ── Build & Start ──────────────────────────────────────────────────────
build_and_start() {
  step "Building Docker images (this may take a few minutes on first run)..."
  docker compose build

  step "Starting all services..."
  docker compose up -d

  step "Waiting for backend to be healthy..."
  for i in {1..20}; do
    if curl -sf http://localhost:8000/health &>/dev/null; then
      break
    fi
    echo -n "."
    sleep 3
  done
  echo ""

  curl -sf http://localhost:8000/health &>/dev/null || warn "Backend health check failed — check: docker compose logs backend"
}

# ── Done ───────────────────────────────────────────────────────────────
print_done() {
  echo -e ""
  echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════╗${RESET}"
  echo -e "${BOLD}${GREEN}║            All services running!         ║${RESET}"
  echo -e "${BOLD}${GREEN}╚══════════════════════════════════════════╝${RESET}"
  echo -e ""
  echo -e "  ${BOLD}Frontend${RESET}   →  ${CYAN}http://localhost:3000${RESET}"
  echo -e "  ${BOLD}Backend${RESET}    →  ${CYAN}http://localhost:8000${RESET}"
  echo -e "  ${BOLD}API Docs${RESET}   →  ${CYAN}http://localhost:8000/docs${RESET}"
  echo -e ""
  echo -e "  Stop all:  ${BOLD}docker compose down${RESET}"
  echo -e "  Logs:      ${BOLD}docker compose logs -f${RESET}"
  echo -e ""
}

# ── Main ───────────────────────────────────────────────────────────────
banner
check_docker
setup_env
build_and_start
print_done
