# @WHO:   self-ai/src/introspection/introspector.py
# @WHAT:  SELF explains WHY it answered the way it did — introspection via Qwen3
# @PART:  self-ai/introspection
# @ENTRY: Introspector.explain_last_answer()

"""Introspector — trace injected experience and articulate reasoning.

Purpose:
    When SELF answers via the unconscious path (UnconsciousInjector),
    the experience vectors are added silently to hidden states — the
    model "feels" the experience without seeing it in the prompt.

    But a key requirement of SELF's architecture is that it can
    EXPLAIN why it answered the way it did. Introspector enables this:
    it looks at the injection log (which nodes were active), retrieves
    their full content, and asks Qwen3 to articulate the reasoning.

    This is introspection: the model examines its own internal state
    and generates a verbal explanation of what influenced it.

Architecture:
    Injection log (from UnconsciousInjector)
        ↓
    Retrieve full UnderstandingNode details
        ↓
    Build introspection prompt with node content
        ↓
    Qwen3 generates explanation in natural language
        ↓
    "Jawaban saya dipengaruhi oleh pengalaman X, di mana saya
     belajar bahwa pola Y selalu mengarah ke Z"

Usage:
    introspector = Introspector(injector, qwen3_model, tokenizer)
    explanation = introspector.explain_last_answer()
    print(explanation)
    # → "Saya menjawab berdasarkan pengalaman tentang signal_flip..."

Design choices:
    - Qwen3 generates the explanation (NOT hardcoded templates)
    - Node content is provided as context (trigger, transformation, examples)
    - Fallback: if Qwen3 unavailable, generate a simple structured summary
    - Works only after an injection has happened (returns None otherwise)
"""

import logging
from typing import Optional

logger = logging.getLogger(__name__)


class Introspector:
    """Trace injected experience and generate natural-language explanations.

    Introspector is the reflective counterpart to UnconsciousInjector.
    While the injector operates silently (unconscious), the Introspector
    can articulate what happened after the fact (conscious reflection).

    This is the "explain" in "explain yourself" — SELF can account for
    its own behavior because it has access to the injection log.

    Attributes:
        injector: The UnconsciousInjector to read injection logs from.
        model: Qwen3 model for generating explanations.
        tokenizer: Qwen3 tokenizer.
    """

    def __init__(self, injector, model=None, tokenizer=None):
        """Initialize the Introspector.

        Args:
            injector: UnconsciousInjector instance — provides injection logs.
            model: Qwen3 model for generating explanations. If None,
                will try to load via get_shared_qwen() lazily.
            tokenizer: Qwen3 tokenizer. If None, loaded with model.
        """
        self.injector = injector
        self._model = model
        self._tokenizer = tokenizer

    def _ensure_model(self):
        """Lazily load Qwen3 model if not provided at init time."""
        if self._model is not None and self._tokenizer is not None:
            return True

        try:
            from derivation.model_registry import get_shared_qwen
            model, tokenizer = get_shared_qwen()
            if model is not None and tokenizer is not None:
                self._model = model
                self._tokenizer = tokenizer
                return True
        except ImportError:
            logger.debug("model_registry not available for Introspector")
        except Exception as e:
            logger.warning("Failed to load Qwen3 for Introspector: %s", e)

        return False

    def explain_last_answer(self, question: str = '') -> Optional[str]:
        """Generate a natural-language explanation of the last injected answer.

        This is the main entry point. After an UnconsciousInjector.active()
        context has been used for generation, call this to get an explanation
        of what experiences influenced the answer.

        The explanation is generated by Qwen3 itself, using the injection
        log as context. This is NOT a hardcoded template — the model
        articulates its reasoning in its own words.

        Args:
            question: Optional — the question that was answered (for context).
                If provided, the explanation will reference the question.

        Returns:
            String explanation in Bahasa Indonesia, or None if no injection
            happened or Qwen3 is unavailable.
        """
        log = self.injector.get_injection_log()

        if not log.get('active'):
            return self._explain_no_injection(question)

        node_details = log.get('node_details', [])
        if not node_details:
            return self._explain_no_injection(question)

        # Try to generate via Qwen3
        if self._ensure_model():
            return self._generate_explanation(question, node_details, log)

        # Fallback: structured summary without LLM
        return self._fallback_explanation(question, node_details, log)

    def _generate_explanation(self, question: str, node_details: list,
                              log: dict) -> Optional[str]:
        """Generate explanation using Qwen3.

        The prompt gives Qwen3 the full content of each injected node
        and asks it to articulate how these experiences influenced the answer.
        """
        prompt = self._build_introspection_prompt(question, node_details, log)

        try:
            inputs = self._tokenizer(
                prompt, return_tensors='pt', max_length=1024, truncation=True
            )

            # Move to model's device
            try:
                device = next(self._model.parameters()).device
                inputs = {k: v.to(device) for k, v in inputs.items()}
            except (StopIteration, AttributeError):
                pass

            outputs = self._model.generate(
                **inputs,
                max_new_tokens=300,
                temperature=0.4,  # Low temperature — we want focused explanation
                do_sample=True,
            )

            # Decode only the new tokens
            new_tokens = outputs[0][inputs['input_ids'].shape[1]:]
            response = self._tokenizer.decode(new_tokens, skip_special_tokens=True)

            if response and response.strip():
                return response.strip()
            return None

        except Exception as e:
            logger.warning("Qwen3 introspection generation failed: %s", e)
            return self._fallback_explanation(question, node_details, log)

    def _build_introspection_prompt(self, question: str,
                                     node_details: list, log: dict) -> str:
        """Build the introspection prompt for Qwen3.

        The prompt includes:
        1. The question that was asked (if available)
        2. Each injected node's content (concept, trigger, transformation, examples)
        3. Instructions to articulate HOW these experiences influenced the answer

        This is NOT a template for the output — it's context for Qwen3
        to generate its own explanation.
        """
        # Build node descriptions
        node_descriptions = []
        for i, nd in enumerate(node_details, 1):
            desc = f"Pengalaman {i}: {nd.get('name', 'tidak bernama')}\n"
            desc += f"  Konsep: {nd.get('concept', '-')}\n"
            desc += f"  Relevansi: {nd.get('score', 0):.2f}\n"
            desc += f"  Akurasi historis: {nd.get('accuracy', 0):.1%}\n"
            desc += f"  Sumber: {nd.get('source', '-')}\n"
            # v35: Lifecycle + epistemic state
            lifecycle = nd.get('lifecycle', 'stable')
            epistemic = nd.get('epistemic', 'observed')
            desc += f"  Status: {lifecycle} / {epistemic}\n"
            # v35: Member roles
            members = nd.get('members', [])
            if members:
                desc += "  Peran struktural:\n"
                for m in members:
                    desc += f"    - {m.get('role', '?')}: {m.get('description', '-')}\n"
            node_descriptions.append(desc)

        nodes_text = '\n'.join(node_descriptions)
        strength = log.get('strength', 0)
        layer = log.get('layer', '?')

        question_part = f''
        if question:
            question_part = f'Pertanyaan yang saya jawab: "{question}"\n\n'

        return f"""Kamu adalah SELF, sebuah AI yang belajar dari pengalaman. Kamu baru saja menjawab sebuah pertanyaan, dan pengalaman-pengalaman berikut secara TIDAK SADAR memengaruhi jawabanmu melalui activation steering (pengalaman di-inject ke hidden state modelmu, bukan di prompt):

{question_part}Pengalaman yang aktif:
{nodes_text}

Kekuatan injection: {strength:.3f}
Layer yang di-inject: {layer}

Jelaskan dalam bahasa Indonesia (3-5 kalimat) MENGAPA kamu menjawab seperti itu, berdasarkan pengalaman-pengalaman di atas. Jangan sekadar daftar — jelaskan BAGAIMANA pengalaman itu memengaruhi penalaranmu. Sebutkan peran struktural mana yang paling mempengaruhi jawabanmu.

Contoh format: 'Jawaban saya dipengaruhi oleh pengalaman tentang X, khususnya peran [trigger/result/exception] yang menyebabkan saya cenderung...'"""

    def _fallback_explanation(self, question: str, node_details: list,
                              log: dict) -> str:
        """Generate a simple structured explanation without LLM.

        Used when Qwen3 is unavailable. This is NOT a hardcoded
        explanation — it's a structured summary that preserves the
        key information from the injection log.

        v35: Includes member role details and governance status.
        """
        parts = []

        if question:
            parts.append(f"Untuk pertanyaan \"{question}\",")

        if len(node_details) == 1:
            nd = node_details[0]
            # v35: Include member roles in explanation
            members = nd.get('members', [])
            member_text = ''
            if members:
                role_descriptions = [
                    f"{m.get('role', '?')}={m.get('description', '-')}"
                    for m in members[:3]
                ]
                member_text = f" ({', '.join(role_descriptions)})"
            parts.append(
                f"jawaban saya dipengaruhi oleh pengalaman tentang "
                f"{nd.get('concept', nd.get('name', 'unknown'))}"
                f"{member_text} "
                f"(relevansi: {nd.get('score', 0):.2f}, "
                f"akurasi: {nd.get('accuracy', 0):.0%}, "
                f"status: {nd.get('lifecycle', 'stable')}/{nd.get('epistemic', 'observed')})"
            )
        else:
            concepts = []
            for nd in node_details:
                c = (
                    f"{nd.get('concept', nd.get('name', '?'))} "
                    f"({nd.get('lifecycle', 'stable')}/{nd.get('epistemic', 'observed')}, "
                    f"relevansi: {nd.get('score', 0):.2f})"
                )
                concepts.append(c)
            parts.append(
                f"jawaban saya dipengaruhi oleh {len(node_details)} pengalaman: "
                + ", ".join(concepts)
            )

        parts.append(
            f"Pengalaman ini di-inject secara tidak sadar ke layer {log.get('layer', '?')} "
            f"dengan kekuatan {log.get('strength', 0):.3f}."
        )

        return " ".join(parts)

    def _explain_no_injection(self, question: str) -> str:
        """Return explanation when no injection happened.

        v35: Also mention if experiences were deactivated (DEPRECATED)
        or not yet verified (NEW).
        """
        if question:
            return (
                f"Untuk pertanyaan \"{question}\", jawaban saya tidak dipengaruhi "
                f"oleh pengalaman tidak sadar — saya menggunakan penalaran sadar "
                f"(conscious path). Pengalaman yang relevan mungkin sudah tidak aktif "
                f"(deprecated) atau belum terverifikasi (new/candidate)."
            )
        return (
            "Tidak ada pengalaman tidak sadar yang aktif saat menjawab — "
            "saya menggunakan penalaran sadar (conscious path). "
            "Pengalaman yang relevan mungkin sudah tidak aktif (deprecated) "
            "atau belum terverifikasi (new/candidate)."
        )
