"""RSVS Protocol definitions for type-safe Rust core access."""
from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class RsvsCoreProtocol(Protocol):
    """Protocol defining the interface the Rust core must satisfy.

    This enables type-safe access to the PyO3-wrapped Rust Rsvs class
    without requiring the actual class to be imported at type-check time.
    """

    def ingest(self, text: str) -> dict: ...
    def query(self, text: str, context: str) -> dict | None: ...
    def similarity(self, label_a: str, label_b: str) -> dict | None: ...
    def appraise(self, text: str) -> dict: ...
    def relate(self, text: str, target: str = "") -> dict: ...
    def node_info(self, label: str) -> dict | None: ...
    def senses(self, label: str) -> list[dict]: ...
    def snapshot_v1(self) -> str: ...
    def consume_events_v1(self) -> str: ...
    def status(self) -> dict: ...
    def save(self, path: str) -> None: ...
    def load(self, path: str) -> None: ...
    def set_domain(self, domain: int) -> None: ...
    def top_atoms(self, n: int) -> list[str]: ...
    def atoms(self) -> list[str]: ...
    def confidence_map(self) -> dict[str, float]: ...
    def __repr__(self) -> str: ...
